In [1]:
import numpy as np
import nibabel as nib
def load_from_nii(nii_file):
    return nib.load(nii_file).get_fdata()

# cortex is an optional import
import cortex
# from cortex import config  #I commented because not used anywhere
#from cortex.options import config
#config.set('webgl_viewopts', "specularity", "0.0")
#config.set("curvature", "contrast", "0.1")
#config.set('webgl', 'colormaps', "/user_data/afluo/anaconda3/envs/pycortex2/share/pycortex/colormaps")

#import h5py
#import matplotlib.pyplot as plt

#import pickle
#import os
#from scipy.io import loadmat

In [2]:
all_subject_rois = dict()
# nsd_root = '/lab_data/tarrlab/common/datasets/NSD'
nsd_root = '/data6/shubham/PC/data/BrinDiVE_fromPrince/nsd_data'

# for subject in [1,2,3,4,5,6,7,8]:
for subject in [1,2,5,7]:
    print("Processing ", subject)
    roi_strings = "HCP_MMP1.nii.gz"
    raw_path = "{}/nsddata_betas/ppdata/subj0{}/func1pt8mm/betas_fithrf_GLMdenoise_RR/ncsnr.nii.gz".format(nsd_root, subject)
    raw_data = load_from_nii(raw_path)
    
    full_path = "{}/nsddata/ppdata/subj0{}/func1pt8mm/roi/{}".format(nsd_root, subject, roi_strings)
    all_roi = load_from_nii(full_path)
    all_rois_long = all_roi.astype(np.int64)
    unique_rois = np.unique(all_rois_long)
    unique_rois = unique_rois[unique_rois>0.5]

    roi_id = []
    roi_ncnsr = []

    for i in unique_rois:
        selected_mask = (all_rois_long==i)
        selected_ncnsr = raw_data[selected_mask]
        roi_id.append(i)
        roi_ncnsr.append(np.nanmean(selected_ncnsr))
    
    roi_id = np.array(roi_id)
    roi_ncnsr = np.array(roi_ncnsr)
    sorted_idx = np.argsort(roi_ncnsr)[::-1]   #give the indices that would sort the given array in discending order
    sorted_roi_id = roi_id[sorted_idx]
    all_subject_rois[subject] = np.copy(sorted_roi_id[:])

    

Processing  1
Processing  2
Processing  5
Processing  7


In [3]:
# Not so good code, should re-write for clarity
roi_list = []
roi_ranks = []
for i in range(1,181):
    roi_list.append(i)
    roi_ranks.append([])
    # for subj in [1,2,3,4,5,6,7,8]:
    for subj in [1,2,5,7]:
        roi_ranks[-1].append(all_subject_rois[subj].tolist().index(i))

roi_list = np.array(roi_list)
roi_ranks = np.array(roi_ranks)
print(roi_ranks)
print(roi_ranks.shape)
roi_ranks_mean = np.mean(roi_ranks, axis=1)
print(roi_ranks_mean.shape)
best = np.argsort(roi_ranks_mean)

# Change the location depending on where you want to save this.
# np.save("/lab_data/tarrlab/afluo/NSD_zscored/best_HCP.npy",roi_list[best])
np.save("/data6/shubham/PC/data/results_preprocessed/best_HCP.npy",roi_list[best])


[[ 33  25  27  30]
 [  3   2   4   0]
 [ 88  88  65  62]
 [ 30  30  25  26]
 [ 21  22  26  38]
 [  7   5  15  11]
 [ 12   3  10   4]
 [158 172 167 174]
 [160 154 159 178]
 [ 62  74  47  35]
 [ 42  51  41  49]
 [ 55  80  70  68]
 [ 29  55  24  52]
 [ 77  77  79  77]
 [ 69  39  62  67]
 [ 19  57  22  22]
 [ 11  21  21  12]
 [ 18  16  18  15]
 [  9  19  11  16]
 [ 15   8   3   7]
 [ 24  26   2  20]
 [ 23  32  17  18]
 [  0   0  20   1]
 [175 159 174 162]
 [ 43  59  74  75]
 [ 56 102 126 109]
 [ 31  44  40  51]
 [ 36  46  61  39]
 [ 50  38  51  32]
 [ 45  36  58  50]
 [ 25  12  33  29]
 [100  96  82  96]
 [ 40  34  42  46]
 [ 65  52  63  59]
 [ 74  48  72  55]
 [140 156 150 140]
 [ 84 103  87  81]
 [ 87  93  78  70]
 [126 151 112 129]
 [157 170 147 157]
 [147 168 161 166]
 [ 71 100  90  86]
 [ 79  98 104 124]
 [107 111 111  97]
 [ 58  60  43  58]
 [ 49  33  37  47]
 [109  86  83  57]
 [ 32  50  35  33]
 [ 44  47  48  48]
 [ 39  23  38  19]
 [162 158 164 167]
 [139 135 108  88]
 [152 166 16